### ISSUE TITLE
How to use pretrained MobilenetV1?

### ISSUE THREAD

**Issue by jingyaa** [YingZhangDUT/Cross-Modal-Projection-Learning#1]
Hello, I want to train pedes dataset. In scripts/train_pedes_mobilenet_cmpm_cmpc.sh, you set a RESTORE_PATH, I download the pretrained mobilenet model from [https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md](url), named MobileNet_v1_1.0_224 and put it in the restore_path. But when I run the the scripts/train_pedes_mobilenet_cmpm_cmpc.sh, there is a problem "No checkpoint Found, Please provide pretrained checkpoint". Can you provide the pretrained model link? Thank you.

**Comment by YingZhangDUT** [comment]
You might also need to have a file named "checkpoint" in the RESTORE_PATH, which has the name of your .ckpt file to guide the restore.

**Comment by jingyaa** [comment]
I have set RESTORE_PATH= pretrained_model/mobilenet_v1/ , the files below this path are ''mobilenet_v1_1.0_224.ckpt.data-00000-of-00001, mobilenet_v1_1.0_224.ckpt.index, mobilenet_v1_1.0_224.ckpt.meta, mobilenet_v1_1.0_224.tflite, mobilenet_v1_1.0_224_eval.pbtxt, mobilenet_v1_1.0_224_frozen.pb, mobilenet_v1_1.0_224_info.txt''. Also has the problem "No checkpoint Found, Please provide pretrained checkpoint".

**Comment by jingyaa** [comment]
Can you provide a link to download your pre-trained mobilenet_v1?

**Comment by YingZhangDUT** [comment]
Well, I download the pre-trained model from http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224.tgz
The problem is a missing file in your restore path, which should be added by yourself.
Please see https://www.tensorflow.org/guide/checkpoints for more detailed usage on checkpoints.

**Comment by jingyaa** [comment]
Can you tell me which file do we miss? And can you send me the missing file? Thank you.

**Comment by kailigo** [comment]
@jingyaa , have you solved the problem? Thanks.

**Comment by jingyaa** [comment]
> @jingyaa , have you solved the problem? Thanks.

Yes, I have solved the problem. You can change the configuration.py as follows. 

def get_init_fn(sess):
    """Returns a function run by the chief worker to warm-start the training.

    Note that the init_fn is only run when initializing the model during the very
    first global step.

    Returns:
      An init function run by the supervisor.
    """
    ck_global_step = 0

    if FLAGS.restore_pretrain:
        
        ckpt = tf.train.get_checkpoint_state(FLAGS.restore_path)
        variables_to_restore = get_variables_to_restore()
        restorer = tf.train.Saver(variables_to_restore)
        restorer.restore(sess, os.path.join(FLAGS.restore_path, 'mobilenet_v1_1.0_224.ckpt'))#'vgg_16.ckpt'))

**Comment by kajal15003** [comment]
@jingyaa Hi, Could you please send this whole function def get_init_fn(sess):?

**Comment by kajal15003** [comment]
> Well, I download the pre-trained model from http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224.tgz
> The problem is a missing file in your restore path, which should be added by yourself.
> Please see https://www.tensorflow.org/guide/checkpoints for more detailed usage on checkpoints.

Could you please give the information about this text file? Could you please upload your text file as a sample?

**Comment by kajal15003** [comment]
> > @jingyaa , have you solved the problem? Thanks.
> 
> Yes, I have solved the problem. You can change the configuration.py as follows.
> 
> def get_init_fn(sess):
> """Returns a function run by the chief worker to warm-start the training.
> 
> ```
> Note that the init_fn is only run when initializing the model during the very
> first global step.
> 
> Returns:
>   An init function run by the supervisor.
> """
> ck_global_step = 0
> 
> if FLAGS.restore_pretrain:
>     
>     ckpt = tf.train.get_checkpoint_state(FLAGS.restore_path)
>     variables_to_restore = get_variables_to_restore()
>     restorer = tf.train.Saver(variables_to_restore)
>     restorer.restore(sess, os.path.join(FLAGS.restore_path, 'mobilenet_v1_1.0_224.ckpt'))#'vgg_16.ckpt'))
> ```

Hi, Could you please send this whole function def get_init_fn(sess):? The problem is ckpt is returning None. Then, below lines are not working.
 ck_pretrain_step = ckpt.model_checkpoint_path.split('/')[-1].split('-')[-1]
            print('Succesfully loaded model from %s at step=%s.' %
                  (ckpt.model_checkpoint_path, ck_pretrain_step))

**Comment by sandareka** [comment]
Hi, 
Even though this is an old and a closed issue, I post what worked for me hoping someone would find it helpful. 
Suppose we want to restore `resnet_v1_152` model.

1. Download and place `resnet_v1_152.ckpt` in `PretrainedModels/resnet_v1_152` folder. 
2. Then set `RESTORE_PATH=PretrainedModels/resnet_v1_152`
3. Create `checkpoint ` file in `PretrainedModels/resnet_v1_152` folder and add the following two lines to it. 
```
model_checkpoint_path: "resnet_v1_152.ckpt"
all_model_checkpoint_paths: "resnet_v1_152.ckpt"
```
Now you should be able to restore the pre-trained model. 

Best Regards!

**Comment by mmmwhy** [comment]
> model_checkopint_path: "resnet_v1_152.ckpt"

should be

model_checkpoint_path: "resnet_v1_152.ckpt"
