### ISSUE TITLE
Can`t reproduce the performance on Flickr30k

### ISSUE THREAD

**Issue by ghost** [YingZhangDUT/Cross-Modal-Projection-Learning#4]
I use your training and testing script on Flickr30k, the model is CMPM_CMPC, but the testing performance is very strange, Evaluating with Cosine Distance...
Text-to-Image Evaluation...
Recall@1   3.86%
Recall@5  12.02%
Recall@10  18.36%
MAP        3.86%
Image-to-Text Evaluation...
Recall@1   3.80%
Recall@5  12.90%
Recall@10  19.50%
MAP        2.62%
That is very strange?

**Comment by cw1091293482** [comment]
I repeat the codes as well, the results I get is below: 

Evaluating with Cosine Distance...
Text-to-Image Evaluation...
Recall@1 0.14%
Recall@5 0.64%
Recall@10 1.34%
MAP 0.14%
Image-to-Text Evaluation...
Recall@1 0.10%
Recall@5 1.00%
Recall@10 1.80%

The training and test dataset is Flickr30k.

Do you have some ideas now?

**Comment by ghost** [comment]
It is the problem about pretrained model, check if you have right restore the pretrained resnet-152 model.
